name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '.github/**'


jobs:
  audit_and_test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install staticcheck
      env:
        GH_URL: https://github.com/dominikh/go-tools/releases/download/2021.1/staticcheck_linux_amd64.tar.gz
      run: |
        cd /tmp && curl -sfL -o staticcheck_linux_amd64.tar.gz "${GH_URL}"
        tar xf staticcheck_linux_amd64.tar.gz && sudo mv staticcheck/staticcheck /usr/local/bin/

    - name: Test
      run: |
        make test
    
    - name: Audit
      run: |
        make audit_helper


  tag:
    needs: audit_and_test
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Install svu
      run: |
        curl -sfL https://install.goreleaser.com/github.com/caarlos0/svu.sh | sudo bash -s -- -b /usr/local/bin

    - name: Push tag
      run: |
        git tag $(svu)
        git push --tags


  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Install goreleaser
      run: |
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sudo bash -s -- -b /usr/local/bin

    - name: Install github-release-notes
      env:
        GH_REL_URL: https://github.com/buchanae/github-release-notes/releases/download/0.2.0/github-release-notes-linux-amd64-0.2.0.tar.gz
      run: |
        cd /tmp && curl -sSL ${GH_REL_URL} | tar xz && sudo mv github-release-notes /usr/local/bin/

    - name: Generate release notes
      run: |
        IFS='/'
        read -a arr <<< "$GITHUB_REPOSITORY"
        ORGANISATION="${arr[0]}"
        REPO="${arr[1]}"
        echo 'CHANGELOG' > /tmp/release.txt
        github-release-notes -org "$ORGANISATION" -repo "$REPO" -since-latest-release -include-author >> /tmp/release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      run: |
        goreleaser release --release-notes=/tmp/release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    